---
name: Test

on:
  push:
    branches:
      - test
jobs:
  Test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Verify node instalation
        run: |
          node -v
